# Generated by Django 6.0.7 on 2026-07-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_seed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='client_tx_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
